In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns
from sklearn.linear_model import LinearRegression

In [2]:
df = pd.read_csv(r'C:/Users/ASUS/Desktop/Subjects/DataSets/1.02. Multiple linear regression.csv')

In [3]:
df.head()

SAT  Rand 1,2,3   GPA
0  1714           1  2.40
1  1664           3  2.52
2  1760           3  2.54
3  1685           3  2.74
4  1693           2  2.83

In [4]:
y = df["GPA"]
x = df[['SAT', 'Rand 1,2,3']]


In [5]:
reg = LinearRegression()

In [6]:
# x = x.values.reshape(-1,1)

In [7]:
reg.fit(x, y)

LinearRegression()

In [8]:
reg.get_params()

{'copy_X': True, 'fit_intercept': True, 'n_jobs': None, 'positive': False}

In [9]:
reg.coef_

array([ 0.00165354, -0.00826982])

In [10]:
reg.intercept_

0.29603261264909486

In [11]:
r2= reg.score(x, y)
r2

0.40668119528142843

In [12]:
n = x.shape[0]
p = x.shape[1]

adj_r2 = 1-(1-r2)*(n-1)/(n-p-1)
adj_r2

0.39203134825134023

In [13]:
prdc_values = pd.DataFrame(data = [[1740, np.random.randint(1,4)],[1800,np.random.randint(1,4)]], columns = ["SAT", "Rand 1,2,3"])
prdc_values

SAT  Rand 1,2,3
0  1740           1
1  1800           2

In [14]:
reg.predict(prdc_values)

array([3.16492552, 3.25586821])

In [15]:
prdc_values["Predict_GPA"] = reg.predict(prdc_values)
prdc_values

SAT  Rand 1,2,3  Predict_GPA
0  1740           1     3.164926
1  1800           2     3.255868

In [16]:
x.iloc[:,0]

0     1714
1     1664
2     1760
3     1685
4     1693
      ... 
79    1936
80    1810
81    1987
82    1962
83    2050
Name: SAT, Length: 84, dtype: int64

In [17]:
from sklearn.feature_selection import f_regression


In [18]:
p_value = f_regression(x, y)[1]
p_value.round(3)

array([0.   , 0.676])

In [19]:
prdc_values["p_values"] = p_value.round(3)

In [20]:
prdc_values


SAT  Rand 1,2,3  Predict_GPA  p_values
0  1740           1     3.164926     0.000
1  1800           2     3.255868     0.676

In [21]:
reg_summary = pd.DataFrame(data=x.columns.values, columns = ['Features'])
reg_summary

Features
0         SAT
1  Rand 1,2,3

In [22]:
reg_summary["Coefficiants"] = reg.coef_
reg_summary

Features  Coefficiants
0         SAT      0.001654
1  Rand 1,2,3     -0.008270

In [23]:
reg_summary['P values'] = p_value.round(3)
reg_summary

Features  Coefficiants  P values
0         SAT      0.001654     0.000
1  Rand 1,2,3     -0.008270     0.676

In [24]:
reg_summary

Features  Coefficiants  P values
0         SAT      0.001654     0.000
1  Rand 1,2,3     -0.008270     0.676

In [25]:
from sklearn.preprocessing import StandardScaler

In [26]:
scaler = StandardScaler()

In [27]:
scaler.fit(x)
scaler.get_params()

{'copy': True, 'with_mean': True, 'with_std': True}

In [58]:
x_scaled = scaler.transform(x)
x_scaled

array([[-1.26338288, -1.24637147],
       [-1.74458431,  1.10632974],
       [-0.82067757,  1.10632974],
       [-1.54247971,  1.10632974],
       [-1.46548748, -0.07002087],
       [-1.68684014, -1.24637147],
       [-0.78218146, -0.07002087],
       [-0.78218146, -1.24637147],
       [-0.51270866, -0.07002087],
       [ 0.04548499,  1.10632974],
       [-1.06127829,  1.10632974],
       [-0.67631715, -0.07002087],
       [-1.06127829, -1.24637147],
       [-1.28263094,  1.10632974],
       [-0.6955652 , -0.07002087],
       [ 0.25721362, -0.07002087],
       [-0.86879772,  1.10632974],
       [-1.64834403, -0.07002087],
       [-0.03150724,  1.10632974],
       [-0.57045283,  1.10632974],
       [-0.81105355,  1.10632974],
       [-1.18639066,  1.10632974],
       [-1.75420834,  1.10632974],
       [-1.52323165, -1.24637147],
       [ 1.23886453, -1.24637147],
       [-0.18549169, -1.24637147],
       [-0.5608288 , -1.24637147],
       [-0.23361183,  1.10632974],
       [ 1.68156984,

In [29]:
reg2 = LinearRegression()
reg2.fit(x_scaled, y)

LinearRegression()

In [32]:
reg2.coef_

array([ 0.17181389, -0.00703007])

In [34]:
reg2.intercept_

3.330238095238095

In [33]:
reg2.score(x_scaled, y)

0.4066811952814283

In [35]:
summary_tab = pd.DataFrame(data= ['Bais', 'SAT', 'Rand 1,2,3'], columns = ['Features'])


In [37]:
summary_tab['weights'] = reg2.intercept_, reg2.coef_[0], reg2.coef_[1]


Features   weights
0        Bais  3.330238
1         SAT  0.171814
2  Rand 1,2,3 -0.007030

In [46]:
Unseen_data = pd.DataFrame(data = [[1740,2], [1800,1]], columns = ['SAT', 'Rand 1,2,3'])
Unseen_data


SAT  Rand 1,2,3
0  1740           2
1  1800           1

In [51]:
Unseen_scaled = scaler.transform(Unseen_data)


In [53]:
Unseen_scaled

array([[-1.01315814, -0.07002087],
       [-0.43571643, -1.24637147]])

In [52]:
reg2.predict(Unseen_scaled)

array([3.1566557 , 3.26413803])

In [86]:
reg_simple = LinearRegression()
x_simple_matrix = x_scaled[:,0].reshape(-1,1)
x_simple_matrix.shape

(84, 1)

In [87]:
reg_simple.fit(x_simple_matrix, y)

LinearRegression()

In [90]:
reg_simple.predict(Unseen_scaled[:,0].reshape(-1,1))

array([3.15593751, 3.25527879])

In [68]:
x_scaled

array([[-1.26338288],
       [-1.74458431],
       [-0.82067757],
       [-1.54247971],
       [-1.46548748],
       [-1.68684014],
       [-0.78218146],
       [-0.78218146],
       [-0.51270866],
       [ 0.04548499],
       [-1.06127829],
       [-0.67631715],
       [-1.06127829],
       [-1.28263094],
       [-0.6955652 ],
       [ 0.25721362],
       [-0.86879772],
       [-1.64834403],
       [-0.03150724],
       [-0.57045283],
       [-0.81105355],
       [-1.18639066],
       [-1.75420834],
       [-1.52323165],
       [ 1.23886453],
       [-0.18549169],
       [-0.5608288 ],
       [-0.23361183],
       [ 1.68156984],
       [-0.4934606 ],
       [-0.73406132],
       [ 0.85390339],
       [-0.67631715],
       [ 0.09360513],
       [ 0.33420585],
       [ 0.03586096],
       [-0.35872421],
       [ 1.04638396],
       [-0.65706909],
       [-0.13737155],
       [ 0.18984542],
       [ 0.04548499],
       [ 1.1618723 ],
       [-1.37887123],
       [ 1.39284898],
       [ 0

In [70]:
x_scaled.shape

(84, 1)

In [71]:
reg.fit(x_scaled, y)

LinearRegression()

In [72]:
reg.coef_

array([0.1720369])

In [73]:
reg.intercept_

3.330238095238095

In [74]:
reg.score(x_scaled, y )

0.40600391479679754

In [79]:
Unseen_scaled[:,0]

array([-1.01315814, -0.43571643])

In [82]:
reg.predict(Unseen_scaled[:,0].reshape(-1, 1))

array([3.15593751, 3.25527879])