In [1]:
import numpy as np
import math

In [2]:
#1.a
np.array([1,-2])

array([ 1, -2])

In [3]:
# 1.b
np.array([-3,5,-7]).reshape(-1,1)

array([[-3],
       [ 5],
       [-7]])

In [4]:
u = np.array([-1,2,9])
v = np.array([3,-1,5])

In [5]:
# 2.a
np.linalg.norm(u)

9.273618495495704

In [6]:
# 2.b
mag = np.linalg.norm(v)
v/mag

array([ 0.50709255, -0.16903085,  0.84515425])

In [7]:
# 2.c
np.dot(u,v)

40

In [8]:
np.linalg.norm(np.eye(1,3))

1.0

In [9]:
# 2.d
costheta = np.dot(u,v)/(np.linalg.norm(u)*np.linalg.norm(v))
theta = np.arccos(costheta)
math.degrees(theta)
#----------------------------------------------------------
sintheta = np.linalg.norm(np.cross(u,v))/(np.linalg.norm(u)*np.linalg.norm(v)*np.linalg.norm(np.eye(1,3)))
theta = np.arcsin(sintheta)
math.degrees(theta)



43.190458397047806

In [10]:
# 2.e
cross = np.cross(u,v)
cross

array([19, 32, -5])

In [11]:
# 2.f
mag = np.linalg.norm(cross)
cross/mag

array([ 0.50599246,  0.85219783, -0.13315591])

In [12]:
# 2.g
u+v

array([ 2,  1, 14])

In [13]:
# 2.h
v-u

array([ 4, -3, -4])

In [14]:
A=np.array([[3,-1,-3],[-5,2,1],[4,4,-6]])
B=np.array([[2,-3,1],[4,-5,3],[3,-1,-2]])


In [15]:
# 3.a
A+B

array([[ 5, -4, -2],
       [-1, -3,  4],
       [ 7,  3, -8]])

In [16]:
# 3.b
A-B

array([[ 1,  2, -4],
       [-9,  7, -2],
       [ 1,  5, -4]])

In [17]:
# 3.c
A*B

array([[  6,   3,  -3],
       [-20, -10,   3],
       [ 12,  -4,  12]])

In [18]:
# 3.d
A@B

array([[ -7,  -1,   6],
       [  1,   4,  -1],
       [  6, -26,  28]])

In [19]:
# 3.e
np.transpose(A)

array([[ 3, -5,  4],
       [-1,  2,  4],
       [-3,  1, -6]])

In [20]:
# 3.f
np.linalg.det(A)

62.00000000000001

In [21]:
# 3.g
np.linalg.inv(A)

array([[-0.25806452, -0.29032258,  0.08064516],
       [-0.41935484, -0.09677419,  0.19354839],
       [-0.4516129 , -0.25806452,  0.01612903]])

In [22]:
# 3.h
inv = np.linalg.inv(A)
det = np.linalg.det(A)
inv*det

array([[-16., -18.,   5.],
       [-26.,  -6.,  12.],
       [-28., -16.,   1.]])

In [23]:
# 3.i
inv = np.linalg.inv(A)
det = np.linalg.det(A)
np.transpose(inv*det)

array([[-16., -26., -28.],
       [-18.,  -6., -16.],
       [  5.,  12.,   1.]])

In [24]:
-A

array([[-3,  1,  3],
       [ 5, -2, -1],
       [-4, -4,  6]])

In [25]:

print("Please enter matrix A row-by-row as follows:")
print("X X X\nX X X\nX X X")
print("A=")
A=np.array([list(map(float, input().split())) for i in range(3)])
print ("A=",A)


        

Please enter matrix A row-by-row as follows:
X X X
X X X
X X X
A=
0.8 0.6 0
-0.6 0.8 0
0 0 1 
A= [[ 0.8  0.6  0. ]
 [-0.6  0.8  0. ]
 [ 0.   0.   1. ]]


In [33]:
def check(A):
    if np.linalg.det(A) != 0:
        if np.allclose(np.transpose(A),np.linalg.inv(A)):
            if np.linalg.det(A) == -1:
                print("A is an orthogonal matrix")
            if np.linalg.det(A) == 1:
                print("A is a special orthogonal matrix")
    if np.array_equal(np.transpose(A),A):
        print("A is a symmetric matrix")
    if np.array_equal(np.transpose(A),-A):
        print("A is a skew-symmetric matrix")
check(A)


A is a special orthogonal matrix
