In [1]:
import numpy as np 
import rvc3python as rv

ModuleNotFoundError: No module named 'rvc3python'

In [48]:
v  = np.array([2, 4, -3]) # np.array([[3, 5, 7]])
# v = v.reshape(-1,1)
v

array([ 2,  4, -3])

In [50]:
u = np.array([1,-2,5])# np.array([[3], [-2], [1]])
# u = u.reshape(-1,1)
u

array([[ 3],
       [-2],
       [ 1]])

In [27]:
np.dot(v,u)

array([[6]])

In [45]:
np.cross(u, v) # both vectors must be rows

array([-14,  13,   8])